server:
  port: 80
  max-http-header-size: 10240



spring:
  mvc:
    view:
      prefix: /pages/

  datasource:
    url: jdbc:mysql://192.168.1.106:3306/guns??characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB


mybatis-plus:
  mapper-locations: classpath:/com/csci/cscipm/module/sys/mapper/*Mapper.xml
